---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBCZehynkAPNuAe3nOJYO9F0ySq3GYKdhy/+9cdfiIMR7cdjyc0WY8ReXSsqLFJ9mCfHDbPcW/i7Lj0DuHy5glP2Rl+i1nB3lBQU553QNI0BvY7xfjwaycrOqMLseaRi3zKrKdJIMqGznuXrzbGqpezOCOa/H20ekxZEsDsIud4IkdRWhwqnHZFfP3fBEty45smZXeUMY+N3gm86dK2zk9k6Oe/jVhipuKYHkp3yIN3AL9K3HAcSHvix4AOeDtj8MF5AUIrMPVwMALS6UjYHZ1jUI2td9MnqGEuS3EL9m+veOrzGKdsvsvzjzCtqVusx2z+1+sdtqw/TOYbChtbfwy8A7LvPwPYJ7uF2HqfERDiPEJzvJVN/LwVQRs2ZNP2JMMUfN5ELJGcVCUQVeGEpiBBpQWPkoLtvkRcqIJ1V0biRjUw9STkgPZOqhrSixzFLKGe7Xn6PwZbxj9aTjixGr7MABErjLGivGFtKmdG66qJDmxHMkODtkH1xWavFFFVMPTpAHzOvYgnpfm4l70NoRRoAFLOMAlaMPvN2qYWr/SaNY5ZX23hX6a/43CKRCEehhuN9o6D3n29Yp2KjxMyRUuBtkpuuzhnKoyQrwZDciPCq4miAwZZqAFUF/IBlrPMKtmQQvMBul1VLFf8PpwatiheighcBlWzNr/bLS7h85FUPIrRUYjDN01V0Yd0QNqwp1r92zYnnuttI9+etPmRnBk=
    admin-user: AgCbrCA4lrM49FvQzRJWjzvZmr+26/L1yD1MtFEBLuA8pCgj9FpBOY0KPVD9elOXG0HwQsfXDFIZDLj6L8i4KKQe6jm9QD/EneVMnLku5l114efg1SJ5GtvOumnv1ecCMH3YUkaRiU4ssDp1GjcRwteduRCyPta5BxLRaW2iaMwwNfEx0CYl0hR17w2F16mM9wI/6zogTZn3lyIpyeQAA2pNYyHbXLoSM7xasYOPHlDxvjT+q9wVz49LxcXkO/RPYYhI72bFvHqaBvMQolzNWVO/VY0v5GyXF6GCKPfQSo+JyiGmq1UF1gJUXAOOlOOhPwsTjzh61f45kcO7+/XrTVVm/mCtC7x6uKRG8d4Tho9RaoBUtxmJOvsbIMWQs08ojIuQPrtNp+cKA7yuE5rBbEI5ijVmMk3SdT3xicdj3zn3sBtn0Ee9Y6pMyS37150osun3AO2mrngV884SjCc7aVqx2oWqbeIum11pWO/ntPxRFfcqqMmOt0OgKGgVJ0H9dbYmax1WiZRxPdaWaWeoPzRbqxIjs0mESG8HGFdIvj3wuKtUmzoiK8mXhThx+U4Ns7+4T0oZnI4/F+5JIOTQ6rqsu0IVTeSidbfsD2pdbk29ULLsEjSAv1JF9Ce5qrLhVBEOEIJ8+gPqEYn20Ak/bfcaHAe2Vdm4jpq/dImbWNZra+FPfMBXlIX+By5+Y/imb/qKJ7aKMg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: monitoring
