---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-db-credentials
  namespace: monitoring
spec:
  encryptedData:
    GF_DATABASE_PASSWORD: AgCv+7lO6GQpxshEIjp6YpcCKrEMFw3V9c9qo524ZOdd37wo3rzdKHPiccTGnZ8TwS9EERzdho0+mUGd+NzG5n8xRLrl1dMiLmtx1gGHI/P46HhU0UW2CEUjMc426SND79Y1BJhPyYi38ZYs/tYqcEaBfDpwUjEM35bUUu9H13rhL6Kv+FYBSCyK0ikHMWAJ8EjEe79VzuoE1qRTmob+fUjMjRlETf3S2aMOhrLVdl8jWkC6y5ui+iM0tfsLwd90BWObZG8FeVUD6EpkEot0C6oyZLNsZJsJoAZACVVLjCFg9UYDYI0YZs2j+6OCye/l3Dk+a081Q8Pu15vm0SAAA620v7+SwGp3J0hAUs+/7j+I8VlZCm+t1WVVxlcYhnF2BuyXQcXdWQz1BBOIegP8Kr3FNFpfLNsO/G6bQnD41b0cxCaLxHC9mwthDuAYitjBDLjXqPlNzYRPrXcAeAKn/vovpFu3BZOEPRq04tzFJzE90lmY3YoV4PuEbx25xEAYkOwc6MepPfAVC7nbrydCYfjsRzxTxshLIKWhwhaSd6Z+k29ZA7iu4RmcrDTeCKFVh/UEL6E/t0dblDrMwNfBSXnHpE9qnPlPx/Za+lPjDivsAu8iZ/bkWfTOS8abhHNH3CEeckmBmyP2kTDLkOll5MZk/UM9NKNoEANZYLAQFDnaDbALe/QUZI3DbHdkWlPzzMThhM2u8t16M3s/H0z/o4g=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-db-credentials
      namespace: monitoring
