apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: platform-argocd
spec:
  project: platform
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 91.4.1
    helm:
      values: |
        crds:
          upgradeJob:
            enabled: true
        grafana:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
          env:
            GF_DATABASE_TYPE: postgres
            GF_DATABASE_HOST: 192.168.50.30:5432
            GF_DATABASE_NAME: grafana
            GF_DATABASE_USER: grafana
            GF_DATABASE_SSL_MODE: disable
          envFromSecrets:
            - name: grafana-db-credentials
          admin:
            existingSecret: grafana-admin-credentials
            userKey: admin-user
            passwordKey: admin-password
          deploymentStrategy:
            type: Recreate
          persistence:
            enabled: false
          plugins:
          - alexanderzobnin-zabbix-app
          - marcusolsson-dynamictext-panel
          additionalDataSources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki-gateway.monitoring.svc:80
            isDefault: false
            jsonData:
              maxLines: 1000
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
            - grafana.wccosta.com.br
            tls:
            - hosts:
              - grafana.wccosta.com.br
              secretName: wccosta-tls
        prometheus:
          prometheusSpec:
            retention: 30d
            resources:
              requests:
                cpu: 250m
                memory: 768Mi
              limits:
                cpu: "2"
                memory: 3Gi
            additionalScrapeConfigs:
              - job_name: proxmox-pve
                static_configs:
                  - targets:
                      - 192.168.50.250:9221
                metrics_path: /metrics
              - job_name: node-192.168.50.250
                static_configs:
                  - targets:
                      - 192.168.50.250:9100
                metrics_path: /metrics
              - job_name: node-rke2-pgdb
                static_configs:
                  - targets:
                      - 192.168.50.30:9100
                metrics_path: /metrics
              - job_name: postgres-rke2-pgdb
                static_configs:
                  - targets:
                      - 192.168.50.30:9187
                metrics_path: /metrics
              - job_name: windows-vm
                static_configs:
                  - targets:
                      - 10.100.20.10:9182
                metrics_path: /metrics
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                  - ReadWriteOnce
                  resources:
                    requests:
                      storage: 20Gi
                  storageClassName: longhorn
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
            - prometheus.wccosta.com.br
            tls:
            - hosts:
              - prometheus.wccosta.com.br
              secretName: wccosta-tls
        alertmanager:
          config:
            global:
              resolve_timeout: 5m
              telegram_api_url: https://api.telegram.org
            route:
              receiver: 'null'
              group_by:
              - namespace
              - alertname
              continue: false
              routes:
              - receiver: telegram
                matchers:
                - severity=~"critical|warning"
                continue: false
              - receiver: "null"
                matchers:
                - alertname="Watchdog"
                continue: false
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
            receivers:
            - name: "null"
            - name: telegram
              telegram_configs:
              - bot_token_file: /etc/alertmanager/secrets/alertmanager-telegram/bot-token
                chat_id: 561566814
                message: |
                  {{ range .Alerts }}
                  *Alert:* {{ .Labels.alertname }}
                  *Summary:* {{ .Annotations.summary }}
                  *Severity:* {{ .Labels.severity }}
                  *Namespace:* {{ .Labels.namespace }}
                  *Description:* {{ .Annotations.description }}
                  {{ end }}
            inhibit_rules:
            - source_matchers:
              - severity="critical"
              target_matchers:
              - severity=~"warning|info"
              equal:
              - namespace
              - alertname
            - source_matchers:
              - severity="warning"
              target_matchers:
              - severity="info"
              equal:
              - namespace
              - alertname
            - source_matchers:
              - alertname="InfoInhibitor"
              target_matchers:
              - severity="info"
              equal:
              - namespace
            - target_matchers:
              - alertname="InfoInhibitor"
          alertmanagerSpec:
            secrets:
            - alertmanager-telegram
        defaultRules:
          disabled:
            KubeCPUOvercommit: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
