apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: platform-argocd
spec:
  project: platform
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 81.5.0
    helm:
      values: |
        grafana:
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: longhorn
          plugins:
          - alexanderzobnin-zabbix-app
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
            - grafana.wcrpc.lan
            tls:
            - hosts:
              - grafana.wcrpc.lan
              secretName: wcrpc-tls
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                  - ReadWriteOnce
                  resources:
                    requests:
                      storage: 20Gi
                  storageClassName: longhorn
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
            - prometheus.wcrpc.lan
            tls:
            - hosts:
              - prometheus.wcrpc.lan
              secretName: wcrpc-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
