apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix
  namespace: platform-argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=false
spec:
  project: platform
  source:
    repoURL: https://zabbix-community.github.io/helm-zabbix
    chart: zabbix
    targetRevision: 7.0.12
    helm:
      values: |
        postgresql:
          persistence:
            enabled: true
            storageClass: longhorn
            storageSize: 10Gi
        zabbixImageTag: ubuntu-7.0.27
        zabbixWeb:
  zabbixServerHost: zabbix-zabbix-server
  zabbixServerPort: 10051
  extraEnv:
    - name: ZBX_SERVER_HOST
      value: zabbix-zabbix-server
    - name: ZBX_SERVER_PORT
      value: "10051"
  service:
    nodePort: 30082
    type: NodePort
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - host: zabbix.wcrpc.lan
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - zabbix.wcrpc.lan
      secretName: wcrpc-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: zabbix
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.persistentVolumeClaimRetentionPolicy
        - .spec.podManagementPolicy
        - .spec.revisionHistoryLimit
        - .spec.updateStrategy
        - .spec.volumeClaimTemplates
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
