apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix
  namespace: platform-argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=false
spec:
  project: platform
  source:
    repoURL: https://zabbix-community.github.io/helm-zabbix
    chart: zabbix
    targetRevision: 7.0.12
    helm:
      values: |
        postgresql:
          persistence:
            enabled: true
            storageClass: longhorn
            storageSize: 10Gi
        zabbixImageTag: ubuntu-7.0.26
        zabbixWeb:
          zabbixServerHost: zabbix-zabbix-server
          zabbixServerPort: 10051
          service:
            nodePort: 30082
            type: NodePort
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
            - host: zabbix.wcrpc.lan
              paths:
              - path: /
                pathType: Prefix
            tls:
            - hosts:
              - zabbix.wcrpc.lan
              secretName: wcrpc-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: zabbix
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.persistentVolumeClaimRetentionPolicy
        - .spec.podManagementPolicy
        - .spec.revisionHistoryLimit
        - .spec.updateStrategy
        - .spec.volumeClaimTemplates[]?.status
        - .spec.volumeClaimTemplates[]?.metadata.annotations
        - .spec.volumeClaimTemplates[]?.metadata.labels
        - .spec.volumeClaimTemplates[]?.spec.storageClassName
        - .spec.volumeClaimTemplates[]?.spec.volumeMode
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
