grafana:
  deploymentStrategy:
    type: Recreate
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: longhorn
  plugins:
  - alexanderzobnin-zabbix-app
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - grafana.wccosta.com.br
    tls:
    - hosts:
      - grafana.wccosta.com.br
      secretName: wccosta-tls
prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: longhorn
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
      - prometheus.wccosta.com.br
      tls:
      - hosts:
        - prometheus.wccosta.com.br
        secretName: wccosta-tls
