apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: wcrpc-ca-issuer
spec:
  ca:
    secretName: wcrpc-ca-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wcrpc-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: wcrpc.lan CA
  secretName: wcrpc-ca-tls
  duration: 87600h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
