postgresql:
  enabled: false
postgresAccess:
  existingSecretName: "zabbix-db-access"
  secretHostKey: "host"
  secretPortKey: "port"
  secretUserKey: "user"
  secretPasswordKey: "password"
  secretDBKey: "dbname"
zabbixImageTag: ubuntu-7.0.29
zabbixWeb:
  zabbixServerHost: zabbix-zabbix-server
  zabbixServerPort: 10051
  extraEnv:
    - name: ZBX_SERVER_HOST
      value: zabbix-zabbix-server
    - name: ZBX_SERVER_PORT
      value: "10051"
  service:
    nodePort: 30082
    type: NodePort
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - host: zabbix.wccosta.com.br
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - zabbix.wccosta.com.br
      secretName: wccosta-tls
