apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-webui
  namespace: ollama
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ai.wcrpc.lan
    secretName: wcrpc-tls
  rules:
  - host: ai.wcrpc.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              number: 80
