apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-webui
  namespace: ollama
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - ai.wcrpc.lan
    secretName: wcrpc-tls
  rules:
  - host: ai.wcrpc.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: open-webui
            port:
              number: 80
