apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  name: daily-backup
  task: backup
  cron: "0 3 * * *"
  retain: 7
  concurrency: 1
  groups:
    - default
