apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - auth-schema-configmap.yaml
  - auth-deploy.yaml
  - auth-svc.yaml
  - recursor-deploy.yaml
  - recursor-svc.yaml
  - ingress.yaml
  - powerdns-zone-setup-job.yaml
