apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: platform-argocd
data:
  server.side.diff.enabled: "false"
  resource.customizations.ignoreDifferences.apps_StatefulSet: |
    jqPathExpressions:
      - .spec.persistentVolumeClaimRetentionPolicy
