apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: platform-argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
  - host: argocd.wcrpc.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
  tls:
  - hosts:
    - argocd.wcrpc.lan
    secretName: wcrpc-tls
