apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: platform-argocd
spec:
  template:
    spec:
      initContainers:
      - name: copyutil
        command: ["sh", "-c"]
        args:
          - /bin/cp --update=none /usr/local/bin/argocd /var/run/argocd/argocd && /bin/ln -sf /var/run/argocd/argocd /var/run/argocd/argocd-cmp-server
